name: Pull Request Restriction

on:
  pull_request:
    branches:
      - '*'

jobs:
  restrict_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from allowed branches
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"
          
          # Define allowed source and target branches
          ALLOWED_SOURCE_BRANCH="develop"
          ALLOWED_TARGET_BRANCH="premain"
          
          if [ "$SOURCE_BRANCH" != "$ALLOWED_SOURCE_BRANCH" ]; then
            echo "No se permite hacer pull request desde esta rama como rama de origen."
            exit 1
          fi
          
          if [ "$TARGET_BRANCH" != "$ALLOWED_TARGET_BRANCH" ]; then
            echo "No se permite hacer pull request a esta rama como rama de destino."
            exit 1
          fi
